### PR TITLE
Add user displayname to newsitems

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
This is a temporary solution until we implemented my profiles extension.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Sounds good, but let's make it slightly less red. ;-)

**Comment by bobdenotter** [comment]
.. or is that just the screenshot where it looks odd?

**Comment by PhillippOhlandt** [comment]
Its the normal red as on the current homepage.

**Comment by PhillippOhlandt** [comment]
I just added the name to the paragraph.

**Comment by bobdenotter** [comment]
Whoop!

**Pull request merged**
